#!/usr/bin/env python3
"""
Conver .bf brainfuck string into font encoded .pdf or vice versa
"""
import sys
from xfuck import brainfuck
from xfuck.bf_to_xf import bf_file_2_pdf
from xfuck.xf2bf import xf2bf
#from pprint import pprint
#from pdfrw import PdfReader
#from xfuck.fonts import get_key

def main(argv):
    filepath = ""
    if len(argv) >= 1:
        a0 = argv[0]
        if ".bf" in a0:
            print("Brainfuck source file, converting into xfuck-pdf")
            r = bf_file_2_pdf(a0)
            print("Created result xfuck-pdf: %s" % r)
        elif ".pdf" in a0:
            #print("PDF source file")
            filepath = a0
            brainfuck.evaluate(xf2bf(filepath))
        else:
            print("use: xfk path/to/source.(bf|pdf)")
    else:
        print("No arguments")

if __name__ == '__main__':
    main(sys.argv[1:])



"""
r = PdfReader(sys.argv[1], decompress=True)
key = get_key(r)
keys = list(key.keys())


brainfuck_chars = "><+-.,[]"

src = ""

for p in r.pages:
  for token in p.Contents.stream.replace("\n", "").split(" "):
      if token not in key:
          continue
      src += brainfuck_chars[keys.index(token)]

if len(sys.argv) > 2:
    skip = int(sys.argv[2])
else:
    skip = 0

brainfuck.evaluate(src[skip+8:])
"""
