#!/usr/bin/env python3

import sys

from pdfrw import PdfReader
from xfuck.fonts import get_key
from xfuck import brainfuck

#TODO: get rid of white space

r = PdfReader(sys.argv[1], decompress=True)
key = get_key(r)
keys = list(key.keys())

from pprint import pprint

brainfuck_chars = "><+-.,[]"

src = ""

for token in r.pages[0].Contents.stream.replace("\n", "").split(" "):
    if token not in key:
        continue
    src += brainfuck_chars[keys.index(token)]

if len(sys.argv) > 2:
    skip = int(sys.argv[2])
else:
    skip = 0

brainfuck.evaluate(src[skip+8:])
#pprint(brainfuck_chars[r.pages[0].Contents.stream.split().index())
